Repository NeuromatchAcademy/course-content, pull requests merged in 2020-06, with the labels that each got.

#61 Add new workflow for checking notebooks during pull request on master
  .github/workflows/jupyternotebook.yml
  .github/workflows/notebook-pr.yaml
  ci/process_notebooks.py
Labels: Infrastructure

#63 Enhanced tutorial PR workflow
  .github/workflows/notebook-pr.yaml
  ci/process_notebooks.py
  tutorials/reviewing-tutorials.md
Labels: Guidance, Infrastructure

#64 Add directories for each day's tutorial content
  tutorials/W1D1-ModelTypes/README.md
  tutorials/W1D2-ModelingPractice/README.md
  tutorials/W1D3-ModelFitting/README.md
  tutorials/W1D4-MachineLearning/README.md
  tutorials/W1D5-DimensionalityReduction/README.md
  tutorials/W2D1-BayesianStatistics/README.md
  tutorials/W2D2-LinearSystems/README.md
  tutorials/W2D3-DecisionMaking/README.md
  tutorials/W2D4-OptimalControl/README.md
  tutorials/W2D5-ReinforcementLearning/README.md
  tutorials/W3D1-RealNeurons/README.md
  tutorials/W3D2-DynamicNetworks/README.md
  tutorials/W3D3-NetworkCausality/README.md
  tutorials/W3D4-DeepLearning1/README.md
  tutorials/W3D5-DeepLearning2/README.md
Labels: Infrastructure

#70 Added link to Exercises with Solutions demo and Colab-Github Workflow
  tutorials/writing-tutorials.md
Labels: Guidance

#71 Filter student versions from notebook workflow
  ci/process_notebooks.py
Labels: Infrastructure

#87 Look for Colab badges and redirect them to master
  ci/process_notebooks.py
Labels: Infrastructure

#100 Fix two issues in tutorial workflow
  .github/workflows/notebook-pr.yaml
  ci/process_notebooks.py
Labels: Infrastructure

#101 Replace W1D1 tutorials to pick up fixed workflow processing
  tutorials/W1D1-ModelTypes/W1D1_Tutorial1.ipynb
  tutorials/W1D1-ModelTypes/W1D1_Tutorial2.ipynb
  tutorials/W1D1-ModelTypes/W1D1_Tutorial3.ipynb
  tutorials/W1D1-ModelTypes/static/W1D1_Tutorial2_Solution_f0c3783f_0.png
  tutorials/W1D1-ModelTypes/student/W1D1_Tutorial1.ipynb
  tutorials/W1D1-ModelTypes/student/W1D1_Tutorial2.ipynb
  tutorials/W1D1-ModelTypes/student/W1D1_Tutorial3.ipynb
Labels: Tutorial

#98 Add W1D2 Tutorials
  tutorials/W1D2-ModelingPractice/W1D2_Tutorial1.ipynb
  tutorials/W1D2-ModelingPractice/W1D2_Tutorial2.ipynb
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_113598e7_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_22f16120_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_4546b67a_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_4ba396ff_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_50b86d87_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_587560e9_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_a6875290_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_b67a48c4_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_cc8f4397_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_cd613629_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_d5d3d6dd_0.png
  tutorials/W1D2-ModelingPractice/static/W1D2_Tutorial1_Solution_e54398a6_0.png
  tutorials/W1D2-ModelingPractice/student/W1D2_Tutorial1.ipynb
  tutorials/W1D2-ModelingPractice/student/W1D2_Tutorial2.ipynb
Labels: Tutorial

#104 Add W1D3 tutorials
   tutorials/W1D3-ModelFitting/W1D3_Tutorial1.ipynb
  tutorials/W1D3-ModelFitting/W1D3_Tutorial1.ipynb
  tutorials/W1D3-ModelFitting/W1D3_Tutorial2.ipynb
  tutorials/W1D3-ModelFitting/W1D3_Tutorial3.ipynb
  tutorials/W1D3-ModelFitting/W1D3_Tutorial4.ipynb
  tutorials/W1D3-ModelFitting/W1D3_Tutorial5.ipynb
  tutorials/W1D3-ModelFitting/W1D3_Tutorial6.ipynb
  tutorials/W1D3-ModelFitting/W1D3_Tutorial7.ipynb
  tutorials/W1D3-ModelFitting/static/W1D3_Tutorial5_Solution_341595ca_0.png
  tutorials/W1D3-ModelFitting/static/W1D3_Tutorial5_Solution_e8db9e7e_0.png
  tutorials/W1D3-ModelFitting/static/W1D3_Tutorial5_Solution_e8db9e7e_2.png
  tutorials/W1D3-ModelFitting/static/W1D3_Tutorial6_Solution_b22019c5_0.png
  tutorials/W1D3-ModelFitting/static/W1D3_Tutorial6_Solution_b22019c5_2.png
  tutorials/W1D3-ModelFitting/static/W1D3_Tutorial6_Solution_fa72c18e_0.png
  tutorials/W1D3-ModelFitting/static/W1D3_Tutorial7_Solution_0251b23c_0.png
  tutorials/W1D3-ModelFitting/static/W1D3_Tutorial7_Solution_cf15e1ca_0.png
  tutorials/W1D3-ModelFitting/student/W1D3_Tutorial1.ipynb
  tutorials/W1D3-ModelFitting/student/W1D3_Tutorial2.ipynb
  tutorials/W1D3-ModelFitting/student/W1D3_Tutorial3.ipynb
  tutorials/W1D3-ModelFitting/student/W1D3_Tutorial4.ipynb
  tutorials/W1D3-ModelFitting/student/W1D3_Tutorial5.ipynb
  tutorials/W1D3-ModelFitting/student/W1D3_Tutorial6.ipynb
  tutorials/W1D3-ModelFitting/student/W1D3_Tutorial7.ipynb
Labels: Tutorial

#113 Extract solution code and link from student versions
  .github/workflows/notebook-pr.yaml
  ci/process_notebooks.py
Labels: Infrastructure

#127 Improve failure message for sequential execution check
  ci/process_notebooks.py
Labels: Infrastructure

#135 Update guidance document for the github merge workflow
  ci/process_notebooks.py
  tutorials/reviewing-tutorials.md
Labels: Guidance

#155 Fix student badge redirection
  ci/process_notebooks.py
Labels: Infrastructure
